--
-- PostgreSQL database dump
--

\restrict iE66zSX484qMNOMJGHaRutlxCGWEuKZfZa7qjFjXMH3QvdssAQDhUBPjDvOZgII

-- Dumped from database version 16.2 (Debian 16.2-1.pgdg120+2)
-- Dumped by pg_dump version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: weather; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA weather;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: AlertSubscriptions; Type: TABLE; Schema: weather; Owner: -
--

CREATE TABLE weather."AlertSubscriptions" (
    "Id" integer NOT NULL,
    "LocationId" integer NOT NULL,
    "Email" character varying(255) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


--
-- Name: AlertSubscriptions_Id_seq; Type: SEQUENCE; Schema: weather; Owner: -
--

ALTER TABLE weather."AlertSubscriptions" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME weather."AlertSubscriptions_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Alerts; Type: TABLE; Schema: weather; Owner: -
--

CREATE TABLE weather."Alerts" (
    "Id" integer NOT NULL,
    "Message" character varying(1000) NOT NULL,
    "Severity" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "LocationId" integer NOT NULL
);


--
-- Name: Alerts_Id_seq; Type: SEQUENCE; Schema: weather; Owner: -
--

ALTER TABLE weather."Alerts" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME weather."Alerts_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: DailyWeather; Type: TABLE; Schema: weather; Owner: -
--

CREATE TABLE weather."DailyWeather" (
    "Id" integer NOT NULL,
    "Date" date NOT NULL,
    "ObservedTemperature" double precision,
    "ObservedDescription" text,
    "ObservedFeelsLike" double precision,
    "ObservedHumidity" double precision,
    "ObservedPressure" double precision,
    "ObservedWindSpeed" double precision,
    "ObservedWindDirection" double precision,
    "ObservedVisibility" integer,
    "ObservedUVI" double precision,
    "ObservedSunrise" timestamp with time zone,
    "ObservedSunset" timestamp with time zone,
    "ObservedNextEventNote" text,
    "PredictedDescription" text,
    "PredictedMinTemperature" double precision,
    "PredictedMaxTemperature" double precision,
    "CreatedAtUtc" timestamp with time zone DEFAULT now() NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "PredictedTemperature" double precision,
    "ObservedTimestamp" timestamp with time zone,
    "LocationId" integer NOT NULL
);


--
-- Name: DailyWeather_Id_seq; Type: SEQUENCE; Schema: weather; Owner: -
--

CREATE SEQUENCE weather."DailyWeather_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: DailyWeather_Id_seq; Type: SEQUENCE OWNED BY; Schema: weather; Owner: -
--

ALTER SEQUENCE weather."DailyWeather_Id_seq" OWNED BY weather."DailyWeather"."Id";


--
-- Name: HourlySummaries; Type: TABLE; Schema: weather; Owner: -
--

CREATE TABLE weather."HourlySummaries" (
    "Id" integer NOT NULL,
    "Timestamp" timestamp with time zone NOT NULL,
    "Temperature" double precision NOT NULL,
    "Description" text NOT NULL,
    "LocationId" integer NOT NULL
);


--
-- Name: HourlySummaries_Id_seq; Type: SEQUENCE; Schema: weather; Owner: -
--

ALTER TABLE weather."HourlySummaries" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME weather."HourlySummaries_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Locations; Type: TABLE; Schema: weather; Owner: -
--

CREATE TABLE weather."Locations" (
    "Id" integer NOT NULL,
    "City" character varying(100) NOT NULL,
    "Latitude" double precision NOT NULL,
    "Longitude" double precision NOT NULL,
    "Notes" character varying(500),
    "CreatedAt" timestamp with time zone NOT NULL,
    "Country" text DEFAULT ''::text,
    "ZipCode" text DEFAULT ''::text
);


--
-- Name: Locations_Id_seq; Type: SEQUENCE; Schema: weather; Owner: -
--

ALTER TABLE weather."Locations" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME weather."Locations_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Users; Type: TABLE; Schema: weather; Owner: -
--

CREATE TABLE weather."Users" (
    "Id" integer NOT NULL,
    "Username" character varying(50) NOT NULL,
    "PasswordHash" text NOT NULL
);


--
-- Name: Users_Id_seq; Type: SEQUENCE; Schema: weather; Owner: -
--

ALTER TABLE weather."Users" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME weather."Users_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: DailyWeather Id; Type: DEFAULT; Schema: weather; Owner: -
--

ALTER TABLE ONLY weather."DailyWeather" ALTER COLUMN "Id" SET DEFAULT nextval('weather."DailyWeather_Id_seq"'::regclass);


--
-- Name: DailyWeather DailyWeather_pkey; Type: CONSTRAINT; Schema: weather; Owner: -
--

ALTER TABLE ONLY weather."DailyWeather"
    ADD CONSTRAINT "DailyWeather_pkey" PRIMARY KEY ("Id");


--
-- Name: AlertSubscriptions PK_AlertSubscriptions; Type: CONSTRAINT; Schema: weather; Owner: -
--

ALTER TABLE ONLY weather."AlertSubscriptions"
    ADD CONSTRAINT "PK_AlertSubscriptions" PRIMARY KEY ("Id");


--
-- Name: Alerts PK_Alerts; Type: CONSTRAINT; Schema: weather; Owner: -
--

ALTER TABLE ONLY weather."Alerts"
    ADD CONSTRAINT "PK_Alerts" PRIMARY KEY ("Id");


--
-- Name: HourlySummaries PK_HourlySummaries; Type: CONSTRAINT; Schema: weather; Owner: -
--

ALTER TABLE ONLY weather."HourlySummaries"
    ADD CONSTRAINT "PK_HourlySummaries" PRIMARY KEY ("Id");


--
-- Name: Locations PK_Locations; Type: CONSTRAINT; Schema: weather; Owner: -
--

ALTER TABLE ONLY weather."Locations"
    ADD CONSTRAINT "PK_Locations" PRIMARY KEY ("Id");


--
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: weather; Owner: -
--

ALTER TABLE ONLY weather."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- Name: IX_AlertSubscriptions_LocationId_Email; Type: INDEX; Schema: weather; Owner: -
--

CREATE UNIQUE INDEX "IX_AlertSubscriptions_LocationId_Email" ON weather."AlertSubscriptions" USING btree ("LocationId", "Email");


--
-- Name: IX_Alerts_CreatedAt; Type: INDEX; Schema: weather; Owner: -
--

CREATE INDEX "IX_Alerts_CreatedAt" ON weather."Alerts" USING btree ("CreatedAt");


--
-- Name: IX_Alerts_LocationId_CreatedAt_Message; Type: INDEX; Schema: weather; Owner: -
--

CREATE UNIQUE INDEX "IX_Alerts_LocationId_CreatedAt_Message" ON weather."Alerts" USING btree ("LocationId", "CreatedAt", "Message");


--
-- Name: IX_DailyWeather_LocationId_Date; Type: INDEX; Schema: weather; Owner: -
--

CREATE UNIQUE INDEX "IX_DailyWeather_LocationId_Date" ON weather."DailyWeather" USING btree ("LocationId", "Date");


--
-- Name: IX_DailyWeather_ObservedTimestamp; Type: INDEX; Schema: weather; Owner: -
--

CREATE INDEX "IX_DailyWeather_ObservedTimestamp" ON weather."DailyWeather" USING btree ("ObservedTimestamp");


--
-- Name: IX_HourlySummaries_LocationId_Timestamp; Type: INDEX; Schema: weather; Owner: -
--

CREATE UNIQUE INDEX "IX_HourlySummaries_LocationId_Timestamp" ON weather."HourlySummaries" USING btree ("LocationId", "Timestamp");


--
-- Name: IX_Locations_City; Type: INDEX; Schema: weather; Owner: -
--

CREATE UNIQUE INDEX "IX_Locations_City" ON weather."Locations" USING btree ("City");


--
-- Name: IX_Users_Username; Type: INDEX; Schema: weather; Owner: -
--

CREATE UNIQUE INDEX "IX_Users_Username" ON weather."Users" USING btree ("Username");


--
-- Name: AlertSubscriptions FK_AlertSubscriptions_Locations_LocationId; Type: FK CONSTRAINT; Schema: weather; Owner: -
--

ALTER TABLE ONLY weather."AlertSubscriptions"
    ADD CONSTRAINT "FK_AlertSubscriptions_Locations_LocationId" FOREIGN KEY ("LocationId") REFERENCES weather."Locations"("Id") ON DELETE CASCADE;


--
-- Name: Alerts FK_Alerts_Locations_LocationId; Type: FK CONSTRAINT; Schema: weather; Owner: -
--

ALTER TABLE ONLY weather."Alerts"
    ADD CONSTRAINT "FK_Alerts_Locations_LocationId" FOREIGN KEY ("LocationId") REFERENCES weather."Locations"("Id") ON DELETE CASCADE;


--
-- Name: DailyWeather FK_DailyWeather_Locations_LocationId; Type: FK CONSTRAINT; Schema: weather; Owner: -
--

ALTER TABLE ONLY weather."DailyWeather"
    ADD CONSTRAINT "FK_DailyWeather_Locations_LocationId" FOREIGN KEY ("LocationId") REFERENCES weather."Locations"("Id") ON DELETE RESTRICT;


--
-- Name: HourlySummaries FK_HourlySummaries_Locations_LocationId; Type: FK CONSTRAINT; Schema: weather; Owner: -
--

ALTER TABLE ONLY weather."HourlySummaries"
    ADD CONSTRAINT "FK_HourlySummaries_Locations_LocationId" FOREIGN KEY ("LocationId") REFERENCES weather."Locations"("Id") ON DELETE RESTRICT;


--
-- PostgreSQL database dump complete
--

\unrestrict iE66zSX484qMNOMJGHaRutlxCGWEuKZfZa7qjFjXMH3QvdssAQDhUBPjDvOZgII

